### ISSUE TITLE
Create dashboard and import datasource

### ISSUE THREAD

**Issue by dingzhaohan** [monitoringartist/grafana-utils#8]
Hi~I want to know how to write the command about create a new dashboard using (uid) after I have created a datasource using api/datasources.
I want to configure grafana using api because I have some spot instances on alicloud, it may be deleted for price reason, and when i created a new instance, i using ansible to deploy prometheus docker, google cadvisor, node exporter on it. In my opinion if there is some automation work, it will much better. Thanks!

**Comment by jangaraj** [comment]
I would say this is not related to this project, so I'm closing this issue. I would say it will be better to ask you Grafana support, [community](https://community.grafana.com/) or read doc (https://grafana.com/docs/grafana/latest/administration/provisioning/ can be your solution).
